---
- name: mcorp box
  hosts: all
  sudo: yes

  roles:
    - common
    - git
    - role: rvm_io.rvm1-ruby
      tags: ruby
      sudo: True
      rvm1_rubies:
        - ruby-head
    - rails-dependencies
    - change_host_name
    - rvm_commons
    - heroku_toolbelt
    - postgres
    # - oracle-java
    # - elasticsearch # will install oracle-java
  # default values
  #vars:
  #  hostname: mcorp-box
