---
- name: "Install Git"
  apt: "name=git state=latest"

- name: "Configure git"
  shell: "{{item}}"
  with_items:
    - git config --global color.ui true
    - git config --global core.editor vim
    - git config --global merge.ff false
    - git config --global pull.rebase true
    - git config --global alias.s 'status -sb'
    - git config --global alias.k 'log --graph --abbrev-commit --decorate --date=local --format=format:"%C(bold blue)%h%C(reset) - %C(bold green)(%ad)%C(reset) %C(white)%s%C(reset) %C(dim white)%C(reset)%C(bold yellow)%d%C(reset) [%an]" --all'
    - git config --global alias.l 'log --graph --abbrev-commit --decorate --date=local --format=format:"%C(bold blue)%h%C(reset) - %C(bold green)(%ad)%C(reset) %C(white)%s%C(reset) %C(dim white)%C(reset)%C(bold yellow)%d%C(reset) [%an]"'