---

- name: Update all packages
  apt: update_cache=yes upgrade=dist

- name: Install common Ubuntu Packages
  apt: "pkg={{item}} state=latest force=yes"
  with_items:
    - build-essential
    - openssl
    - libreadline6
    - libreadline6-dev
    - zlib1g
    - zlib1g-dev
    - libssl-dev
    - libyaml-dev
    - libsqlite3-0
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - autoconf
    - libc6-dev
    - libncurses5-dev
    - automake
    - libtool
    - bison
    - git
    - libffi-dev
    - python-psycopg2
    - nfs-common
    - portmap
    - s3cmd
    - npm
    - language-pack-en
    - language-pack-en-base
    - language-pack-pt
    - language-pack-pt-base

- name: create mcorp dir
  sudo: True
  shell: 'mkdir -p /mcorp'

- name: copy box-reset script
  sudo: True
  template:
    src: box-reset.j2
    mode: "u=rwx,g=rx,o=rx"
    dest: /mcorp/box-reset.sh

- name: using the dark background as default for vim
  sudo: no
  lineinfile: dest=~/.vimrc line="set background=dark" state=present create=yes

- name: Configure Locale
  locale_gen:
    name: pt_BR.UTF-8
    state: present
