---
- name: add key to elastic-search
  apt_key:
    url: https://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present 
    id: D88E42B4
- name: add repositorie
  apt_repository: 
    repo: "deb http://packages.elasticsearch.org/elasticsearch/{{ elasticsearch_version | default('1.5') }}/debian stable main"
    state: present
- name: install elasticsearch
  apt:
    name: elasticsearch
    state: latest
