---
- name: "Install Postgres"
  apt: "pkg={{ item }} state=present"
  with_items:
    - "postgresql-{{ postgres_version | default('9.3') }}"
    - "postgresql-contrib-{{ postgres_version | default('9.3') }}"
    - "postgresql-client-{{ postgres_version | default('9.3') }}"

- postgresql_user: "name={{postgres_db_user}} role_attr_flags=CREATEDB,CREATEROLE,SUPERUSER state=present"
- postgresql_db: "name={{ postgres_db | mandatory }}"
- postgresql_privs: "db={{ postgres_db }} privs=ALL type=schema role={{postgres_db_user}}"