---
- name: "Install Postgres"
  apt: "pkg={{ item }} state=present"
  with_items:
    - "postgresql-{{ postgres_version | default('9.5') }}"
    - "postgresql-contrib-{{ postgres_version | default('9.5') }}"
    - "postgresql-client-{{ postgres_version | default('9.5') }}"

- name: Set postgres user password to default
  become: true
  become_user: postgres
  postgresql_user:
    user: postgres
    login_user: postgres
    password: "{{ postgres_password | default('postgres') }}"

- name: set PGHOST
  become: False
  lineinfile: dest=~/.bashrc line="export PGHOST=\"localhost\""

- name: set PGPASSWORD
  become: False
  lineinfile: dest=~/.bashrc line="export PGPASSWORD=\"postgres\""

- name: set PGUSER
  become: False
  lineinfile: dest=~/.bashrc line="export PGUSER=\"postgres\""
