---
- name: "Install Postgres"
  apt: "pkg={{ item }} state=present"
  with_items:
    - "postgresql-{{ postgres_version | default('9.3') }}"
    - "postgresql-contrib-{{ postgres_version | default('9.3') }}"
    - "postgresql-client-{{ postgres_version | default('9.3') }}"

- name: Set postgres user password to default
  sudo: True
  sudo_user: postgres
  postgresql_user:
    user: postgres
    login_user: postgres
    password: postgres

- name: set PGHOST
  sudo: no
  lineinfile: dest=~/.bashrc line="export PGHOST=\"localhost\""

- name: set PGPASSWORD
  sudo: no
  lineinfile: dest=~/.bashrc line="export PGPASSWORD=\"postgres\""

- name: set PGUSER
  sudo: no
  lineinfile: dest=~/.bashrc line="export PGUSER=\"postgres\""
